### ISSUE TITLE
Use a "type" section

### ISSUE THREAD

**Issue by benjaminpeeters** [macroverse-r/icy#6]
Use a "type" section in template to restreint the values that some variables can take.

For example, the template could be like:

```yaml

default:
  MY_SUPER_INTEGER: 19
  MY_NAME: "John Doe"
  ARE_YOU_WORKING: yes

description:
  MY_SUPER_INTEGER: "My Favorite number"
  MY_NAME: "This variable represents your name"
  ARE_YOU_WORKING: "Variable to monitor if you are working"

type:
  MY_SUPER_INTEGER: integer
  NY_NAME: character
  ARE_YOU_WORKING: boolean


```
