### ISSUE TITLE
Further development with template

### ISSUE THREAD

**Issue by benjaminpeeters** [macroverse-r/icy#7]
Consider being able to have this type of template:

```yaml
config:
  metadata:
    version: "1.0"
    description: "Environment configuration template"
    created: "2025-06-02"
  
  variables:
    MY_SUPER_INTEGER:
      default: 19
      description: "My favorite number"
      type: integer
      required: false
      constraints:
        min: 1
        max: 100
    
    MY_NAME:
      default: "John Doe"
      description: "This variable represents your name"
      type: character
      required: true
      constraints:
        min_length: 2
        max_length: 50
    
    ARE_YOU_WORKING:
      default: true
      description: "Variable to monitor if you are working"
      type: boolean
      required: false
      allowed_values: [true, false]

  settings:
    prefix: ""
    overwrite_existing: false
    validate_types: true
    case_sensitive: true
```
